site_name: "Frame Docs"
site_url: https://frame.dev
# repo_url: 
# repo_name:
nav:
  - Installation: installation.md
  - Architecture:
      - Main: Architecture/_main_/main.md
      - Overview: Architecture/overview.md
      - Components: Architecture/components.md
      - Design Patterns: Architecture/design_patterns.md
  - API:
      - API Reference: API/api_reference.md
      - Frame:
          - Overview: API/frame/frame.md
          - Frame:
            - Framer:
                - Framer: API/frame/framer/framer.md
                - Framer Factory: 
                    - Overview: API/frame/framer/framer_factory.md
                    - API Reference: API/frame/framer/framer_factory_api.md
                - Agency:
                  - Agency: API/frame/framer/agency/agency.md
                  - Action Registry: API/frame/framer/agency/action_registry.md
                  - Default Actions: API/frame/framer/agency/default_actions.md
                  - Tasks:
                    - Task: API/frame/framer/agency/tasks/task.md
                  - Workflow:
                    - Workflow: API/frame/framer/agency/workflow/workflow.md
                    - Workflow Manager: API/frame/framer/agency/workflow/workflow_manager.md
                - Brain:
                    - Brain: API/frame/framer/brain/brain.md
                    - Decision: API/frame/framer/brain/decision/decision.md
                    - Mind:
                      - Mind: API/frame/framer/brain/mind/mind.md
                      - Perception: API/frame/framer/brain/mind/perception/perception.md
                    - Memory: API/frame/framer/brain/memory/memory.md
                    - Memory Adapter: API/frame/framer/brain/memory/memory_adapters/mem0/mem0_adapter.md
                - Soul: API/frame/framer/soul/soul.md
                - Config: API/frame/framer/config.md
            - Framed:
                - Framed: API/frame/framed/framed.md
                - Framed Factory: API/frame/framed/framed_factory.md
                - Config: API/frame/framed/config.md
      - Services:
          - LLM:
              - Main: API/frame/services/llm/main.md
              - Adapter Interface: API/frame/services/llm/llm_adapter_interface.md
          - Memory: API/frame/services/memory/main.md
          - EQ: API/frame/services/eq/main.md
          - Context:
              - Local Context Service: API/frame/services/context/local_context_service.md
              - Shared Context Service: API/frame/services/context/shared_context_service.md
              - Execution Context: API/frame/services/context/execution_context.md
              - Execution Context Service: API/frame/services/context/execution_context_service.md
      - Utils:
          - Log Manager: API/frame/utils/log_manager.md
          - ID Generator: API/frame/utils/id_generator.md
          - LLM Utils: API/frame/utils/llm_utils.md
          - Metrics: API/frame/utils/metrics.md
  - Usage / Quick Start Guide:
    - Basic: Usage/basic/basic_usage.md
    - Testing: Usage/testing/testing.md
    - Advanced: Usage/advanced/advanced_usage.md
  - Plugins: 
    - Overview: plugins/overview.md
    - Plugin Base: plugins/plugin_base.md
    - Search Extract Summarize Plugin: plugins/search_extract_summarize_plugin.md
    - Creating Custom Plugins: plugins/creating_custom_plugins.md
  - CLI: CLI.md
  - Glossary: glossary.md
  - Utils:
    - Plugin Loader: utils/plugin_loader.md
docs_dir: ./docs
site_dir: ../site
theme:
  logo: ../frame-logo-no-text-transparent.png
  homepage: 
  favicon: ../favicon.ico
  name: "material"
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  font:
    code: Roboto
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - content.footnote.tooltips
    - content.footnote.backlink
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.prune 
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.top
plugins:
  - search
  - exclude-search:
      exclude:
        - .git
        - .venv/
        - venv/
        - coverage_html/
        - assets/
        - htmlcov/
  - git-latest-changes
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  - mkdocs-nav-weight:
      section_renamed: false
      index_weight: -10
      warning: true
      reverse: false
      headless_included: false
  - coverage:
      page_path: coverage
      html_report_dir: docs/htmlcov
  - mkdocs-add-teaser
  - pub-social
  - autorefs
  - open-in-new-tab
  - toggle-sidebar
  # - swagger-ui-tag:
  #     background: White
  #     docExpansion: none
  #     filter: ""
  #     syntaxHighlightTheme: monokai
  #     tryItOutEnabled: true
  - roamlinks
  - pub-meta:
      enabled: false
  - section-index
  - pagetree
  - mkdocs-video
  - htmlproofer
  - link-marker
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            paths: [..frame, ..frame\src]
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      cache_safe: true

markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
  - mkdocs-click
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.magiclink
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - pymdownx.snippets
  - mdx_truly_sane_lists
  - mkdocs-click
  - markdown_captions
  - markdown_checklist.extension
